### ISSUE TITLE
Delete base table or view

### ISSUE THREAD

**Issue by tubberd** [mit-pdos/noria#135]
I've been playing Noria in a private little CMS project - and noticed that there
seems to be no way to delete a view or table once it has been installed?
Or is there and i simply overlooked it?
Is this perhaps intentional design?

**Comment by ms705** [comment]
You can remove views! The way to do it is to use the `install_recipe` RPC, but to install a recipe that removes the view definition for the view you want to delete.

(`extend_recipe` is a shorthand for just appending to the list of view definitions, but you can use `install_recipe` to provide an arbitrary new list that overwrites the old list of view definitions. Noria will work out the difference and apply the changes.)

**Comment by tubberd** [comment]
Thanks for the clarification!
I suppose this issue can then be closed?
