### ISSUE TITLE
Async and Sync example links broken in readme

### ISSUE THREAD

**Issue by anandijain** [mit-pdos/noria#158]
Under `Rust Bindings` there is a link to `https://github.com/mit-pdos/noria/blob/master/server/noria/examples/quickstart-async.rs` and `https://github.com/mit-pdos/noria/blob/master/noria/examples/quickstart-sync.rs` 
which are both broken, but I can't find them in `/server/examples` or `/applications/`.

**Comment by jonhoo** [comment]
Oh, yeah, there's no longer a separate sync/async quickstart. They should probably just point to the single quickstart example that's there now! I guess maybe the text there is a little out of date in general if it still talks about the sync bindings :sweat_smile:
