### ISSUE TITLE
Index out of bounds error after changing schema, potentially confusing error 

### ISSUE THREAD

**Issue by anandijain** [mit-pdos/noria#163]
I'm learning Rust+Noria, but I have a simple db (from quickstart.rs) with a table like `Article`, and permanent persistence set. 
I ran into an error after trying to write to the db after having changed the schema, that could potentially be cleared up so that it is more obvious that there is a schema conflict. 

```thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 5 but the index is 5', /home/*/.cargo/registry/src/github.com-1ecc6299db9ec823/noria-dataflow-0.4.0/src/ops/project.rs:239:32```

It is particularly odd, because, say someone else pushed a commit that changed the schema, the new length of columns in the table is not 5, potentially misleading the debugger.

**Comment by jonathanGB** [comment]
Can you tell us the steps? That is, what your first `Article` table looked like, how you migrated to the new schema (and what does the new schema look like), and what did you try to insert?

**Comment by anandijain** [comment]
Hello, I believe this was user error. I think I was incorrectly specifying the `--deployment` tag.
Sorry, closing since I can't recreate the issue.
