### ISSUE TITLE
Can I link my application with noria into a single program? 

### ISSUE THREAD

**Issue by Frozen-Tofu** [mit-pdos/noria#166]
Like sqlite

**Comment by jonhoo** [comment]
Yeah, you can embed Noria by using the `noria-server` crate and `LocalAuthority`. Take a look at https://github.com/mit-pdos/noria/blob/master/server/examples/local-server.rs.

Keep in mind that Noria isn't really production-ready though, so I wouldn't use it for anything much more serious than technical curiosity and experimentation :)

**Comment by Frozen-Tofu** [comment]
Oh thanks!
