### ISSUE TITLE
Question: noria for mobile/desktop apps as embeded database?

### ISSUE THREAD

**Issue by molikto** [mit-pdos/noria#168]
I think mobile apps also faces same problem, database queries are invalidated when an update happens. The mobile ORMs fake "reactive" by [re-query the db](https://developer.android.com/reference/androidx/room/RxRoom#createObservable(androidx.room.RoomDatabase,%20java.lang.String...)). This is slow.

Can noria be adapted to used for mobile? The differences are:

1. mobile db access is much less concurrent.
2. to minimalize memory usage, only the part that is visible to the user is queried (for example a conversation in an chat app). as user scroll the screen, more data is appended using another query. I am not sure what the "upquery" thing exact are, but it sounds like what I have in mind for this case. can this case be handled transparently (and incrementaly) for the user?

**Comment by jonhoo** [comment]
Yeah, in theory you could totally have the server feed updates to the client, which could then apply the incrementally. That's a whole, and huge, project of its own though, and not something that's likely to be implemented here any time soon :)
