### ISSUE TITLE
Fail build

### ISSUE THREAD

**Issue by service-b360** [mit-pdos/noria#178]
https://dev.azure.com/mit-pdos/mit-pdos/_build/results?buildId=433&view=logs&j=095ec1ee-4eeb-50d5-9c40-517c9ce48d7d&t=3b15de4d-c21d-5a30-b4ad-51e3d44e8e05

Build fails with error (bitvec, funty). Please correct the versions of libraries.

**Comment by jonhoo** [comment]
Ah, this is actually a known issue upstream, and not something we can easily fix in this codebase except by holding back future updates. I think the right thing is to wait for https://github.com/bitvecto-rs/bitvec/issues/105 to be resolved :)
