### ISSUE TITLE
SQLite support

### ISSUE THREAD

**Issue by vjpr** [mit-pdos/noria#183]
Such an approach would be great to have in the browser or on mobile.

I'm thinking of the UI state as a bunch of materialized views of sql which stream changes on updates to the db.

Could the SQL-to-data flow algorithm/component be modularized for such a use case?

Could you point me in the right place to look in the code?

**Comment by jonhoo** [comment]
Hi! There's nothing in Noria itself that actually ties it to any particular database. The research prototype I built does all of its own data storage, and its only relation to MySQL is that there is an external shim application that translates between the MySQL protocol and the Noria API: https://github.com/mit-pdos/noria-mysql :)
